# Generated by Django 4.2.2 on 2024-07-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
    ]
