# Generated by Django 4.2.2 on 2024-03-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='camp_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
