# Generated by Django 4.2.2 on 2024-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0002_booking_camp_name_alter_booking_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='availability_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(default='', max_length=20)),
                ('availability_date', models.DateField()),
            ],
        ),
    ]
