# Generated by Django 4.2.2 on 2024-04-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0006_completedbooking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
