# Generated by Django 4.2.2 on 2024-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0008_remove_completedbooking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedbooking',
            name='booking_date',
            field=models.DateField(default=''),
        ),
    ]
