# Generated by Django 4.2.2 on 2024-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0005_completedbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedbooking',
            name='payment_method',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
