# Generated by Django 4.2.2 on 2024-04-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_app', '0017_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability_form',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedbooking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
